version: '3'
services:
  postgreSQL:
    image: postgres:14.5
    container_name: "postgreSQL"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    hostname: postgreSQL